/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as RoadsideAssistanceRouteImport } from './routes/roadside-assistance'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TowingRouteImport } from './routes/towing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsideAssistanceRoute = RoadsideAssistanceRouteImport.update({
  id: '/roadside-assistance',
  path: '/roadside-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TowingRoute = TowingRouteImport.update({
  id: '/towing',
  path: '/towing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/recovery': typeof RecoveryRoute
  '/roadside-assistance': typeof RoadsideAssistanceRoute
  '/services': typeof ServicesRoute
  '/towing': typeof TowingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/recovery': typeof RecoveryRoute
  '/roadside-assistance': typeof RoadsideAssistanceRoute
  '/services': typeof ServicesRoute
  '/towing': typeof TowingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/recovery': typeof RecoveryRoute
  '/roadside-assistance': typeof RoadsideAssistanceRoute
  '/services': typeof ServicesRoute
  '/towing': typeof TowingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/fleet'
    | '/recovery'
    | '/roadside-assistance'
    | '/services'
    | '/towing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/fleet'
    | '/recovery'
    | '/roadside-assistance'
    | '/services'
    | '/towing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/fleet'
    | '/recovery'
    | '/roadside-assistance'
    | '/services'
    | '/towing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  FleetRoute: typeof FleetRoute
  RecoveryRoute: typeof RecoveryRoute
  RoadsideAssistanceRoute: typeof RoadsideAssistanceRoute
  ServicesRoute: typeof ServicesRoute
  TowingRoute: typeof TowingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadside-assistance': {
      id: '/roadside-assistance'
      path: '/roadside-assistance'
      fullPath: '/roadside-assistance'
      preLoaderRoute: typeof RoadsideAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/towing': {
      id: '/towing'
      path: '/towing'
      fullPath: '/towing'
      preLoaderRoute: typeof TowingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  FleetRoute: FleetRoute,
  RecoveryRoute: RecoveryRoute,
  RoadsideAssistanceRoute: RoadsideAssistanceRoute,
  ServicesRoute: ServicesRoute,
  TowingRoute: TowingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
